### PR TITLE
Changes to Sessions.cs

### PR DESCRIPTION
**Pull request by bescoto42**

### CODE REVIEW

**Comment by jhburns** [comment]
@bescoto42 minor linting issue, please fix. 
https://github.com/jhburns/ExperienceCapture/pull/27/checks?check_run_id=288617817#step:4:123

**Comment by jhburns** [comment]
Whoops, closed on accident. My b

**Comment by jhburns** [comment]
Btw, if you make another commit and push to this branch it will automatically update the PR and rerun the CI test. Keep up the good work!

**Comment by bescoto42** [comment]
I fixed the issue

**Comment by jhburns** [comment]
Excellent, merged

**Pull request merged**
